server:
  port: 9001

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://wogusdb.cjqirdiko8gp.ap-northeast-2.rds.amazonaws.com/planet_dev_DB?autoReconnect=true # 변경해주세요
    username: wogus4048 # 변경해주세요
    password: k10047942 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc  .Driver # mysql 5버전
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.naver.com
    port: 465
    username: dkrak3212@naver.com
    password: mskim@!!123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

          #  required: true
          #connectiontimeout: 5000
          #timeout: 5000
          #writetimeout: 5000
          ssl:
          #trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: 127.0.0.1

cloud:
  aws:
    s3:
      bucket: sesac-planet
    credentials:
      accesskey: AKIAY6THU26VMTG4ZP75
      secretkey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false